on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd:latest .
    - name: push to dockerhub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/cicd:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: deploy
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/cicd
        chmod 600 ~/.ssh/cicd
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/cicd ubuntu@54.236.26.160 << '+'
        
        sudo docker stop cicd || true
        sudo docker rm cicd || true
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cicd:latest
        sudo docker run -d --name cicd -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/midterm:latest
        +

    - name: successful completion
      run: echo "Deployment to EC2 complete."
